basePath: /
info:
  contact:
    email: hello@ariefsn.dev
    name: API Support
    url: https://ariefsn.dev
  description: API Upwork Service.
  title: Upwork Service
  version: "3.0"
paths: {}
securityDefinitions:
  Bearer:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
